name: Generar serpiente

on:
  schedule:
    - cron: "0 */6 * * *"  # Ejecutar cada 6 horas
  workflow_dispatch:  # Permite ejecutar el flujo manualmente desde la pestaña de acciones

jobs:
  build:
    runs-on: ubuntu-22.04  # Usamos ubuntu-22.04 en lugar de ubuntu-latest para evitar la futura actualización a ubuntu-24.04

    steps:
      # 1. Verificamos que el repositorio esté disponible
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Generamos el gif y el svg de la serpiente
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master  # Usamos la rama master de Platane/snk
        id: snake-gif
        with:
          github_user_name: OtiliaNicola  # Tu nombre de usuario de GitHub

      # 3. Verificamos el estado de los cambios
      - run: git status

      # 4. Hacemos el push de los cambios a la rama 'output'
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0  # Usamos una versión estable de esta acción
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # El token para hacer push
          branch: output  # Rama 'output' donde se almacenan los archivos generados
          force: true

      # 5. Desplegamos los archivos generados en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Rama de destino para GitHub Pages
          build_dir: dist  # El directorio con los archivos generados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # El token de GitHub para autenticación
